name: Build-Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: target
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
