name: Static_code Cppcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install cppcheck
      run: sudo apt -y install cppcheck
      
    - name: Static_analysis
      run: cppcheck 3_Implementation
      

