name: Static_code Cppcheck 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
 
    - name: static_analysis
      run: cppcheck --enable=all 3_Implementation

