name: Build-linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: target
      run: gcc Departmental.c main.c -o Departmental.o
      
    - name: run
      run: ./Departmental.o
      
    - name: make distcheck
      run: make distcheck
